// flow-typed signature: 7e8ab9d95dff1e6c47ed10725b240f95
// flow-typed version: <<STUB>>/clientjs_v^0.1.11/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clientjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clientjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clientjs/dist/client.min' {
  declare module.exports: any;
}

declare module 'clientjs/gulpfile' {
  declare module.exports: any;
}

declare module 'clientjs/karma/aircover.conf' {
  declare module.exports: any;
}

declare module 'clientjs/karma/drone.conf' {
  declare module.exports: any;
}

declare module 'clientjs/karma/local.conf' {
  declare module.exports: any;
}

declare module 'clientjs/scripts/install' {
  declare module.exports: any;
}

declare module 'clientjs/scripts/test' {
  declare module.exports: any;
}

declare module 'clientjs/specs/ClientJSpec' {
  declare module.exports: any;
}

declare module 'clientjs/src/client' {
  declare module.exports: any;
}

declare module 'clientjs/src/vendor/deployJava' {
  declare module.exports: any;
}

declare module 'clientjs/src/vendor/fontdetect' {
  declare module.exports: any;
}

declare module 'clientjs/src/vendor/murmurhash3' {
  declare module.exports: any;
}

declare module 'clientjs/src/vendor/swfobject' {
  declare module.exports: any;
}

declare module 'clientjs/src/vendor/ua-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clientjs/dist/client.min.js' {
  declare module.exports: $Exports<'clientjs/dist/client.min'>;
}
declare module 'clientjs/gulpfile.js' {
  declare module.exports: $Exports<'clientjs/gulpfile'>;
}
declare module 'clientjs/karma/aircover.conf.js' {
  declare module.exports: $Exports<'clientjs/karma/aircover.conf'>;
}
declare module 'clientjs/karma/drone.conf.js' {
  declare module.exports: $Exports<'clientjs/karma/drone.conf'>;
}
declare module 'clientjs/karma/local.conf.js' {
  declare module.exports: $Exports<'clientjs/karma/local.conf'>;
}
declare module 'clientjs/scripts/install.js' {
  declare module.exports: $Exports<'clientjs/scripts/install'>;
}
declare module 'clientjs/scripts/test.js' {
  declare module.exports: $Exports<'clientjs/scripts/test'>;
}
declare module 'clientjs/specs/ClientJSpec.js' {
  declare module.exports: $Exports<'clientjs/specs/ClientJSpec'>;
}
declare module 'clientjs/src/client.js' {
  declare module.exports: $Exports<'clientjs/src/client'>;
}
declare module 'clientjs/src/vendor/deployJava.js' {
  declare module.exports: $Exports<'clientjs/src/vendor/deployJava'>;
}
declare module 'clientjs/src/vendor/fontdetect.js' {
  declare module.exports: $Exports<'clientjs/src/vendor/fontdetect'>;
}
declare module 'clientjs/src/vendor/murmurhash3.js' {
  declare module.exports: $Exports<'clientjs/src/vendor/murmurhash3'>;
}
declare module 'clientjs/src/vendor/swfobject.js' {
  declare module.exports: $Exports<'clientjs/src/vendor/swfobject'>;
}
declare module 'clientjs/src/vendor/ua-parser.js' {
  declare module.exports: $Exports<'clientjs/src/vendor/ua-parser'>;
}
