// flow-typed signature: ff059030eadf29c6a42b6cdd812b5f66
// flow-typed version: <<STUB>>/csvtojson_v^2.0.8/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csvtojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csvtojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csvtojson/bin/csvtojson' {
  declare module.exports: any;
}

declare module 'csvtojson/bin/genCsv' {
  declare module.exports: any;
}

declare module 'csvtojson/browser/browser' {
  declare module.exports: any;
}

declare module 'csvtojson/coverage/block-navigation' {
  declare module.exports: any;
}

declare module 'csvtojson/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'csvtojson/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'csvtojson/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'csvtojson/coverage/prettify' {
  declare module.exports: any;
}

declare module 'csvtojson/coverage/sorter' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/Converter' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/CSVError' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/csvline' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/dataToCSVLine' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/defaultParsers/index' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/defaultParsers/parser_array' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/defaultParsers/parser_flat' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/defaultParsers/parser_json' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/defaultParsers/parser_jsonarray' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/defaultParsers/parser_omit' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/defParam' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/fileline' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/fileLineToCSVLine' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/filterRow' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/getDelimiter' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/getEol' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/index' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/linesToJson' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/parser' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/parserMgr' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/rowSplit' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/worker' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/core/workerMgr' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/index' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/interfaces/cli/index' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/interfaces/cli/main' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/interfaces/index' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/interfaces/web/index' {
  declare module.exports: any;
}

declare module 'csvtojson/v1/interfaces/web/webServer' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/Converter' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/CSVError' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/dataClean' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/fileline' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/getEol' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/index' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/lineToJson' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/Parameters' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/ParseRuntime' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/ProcessFork' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/Processor' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/ProcessorLocal' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/Result' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/rowSplit' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/util' {
  declare module.exports: any;
}

declare module 'csvtojson/v2/worker' {
  declare module.exports: any;
}

declare module 'csvtojson/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csvtojson/bin/csvtojson.js' {
  declare module.exports: $Exports<'csvtojson/bin/csvtojson'>;
}
declare module 'csvtojson/bin/genCsv.js' {
  declare module.exports: $Exports<'csvtojson/bin/genCsv'>;
}
declare module 'csvtojson/browser/browser.js' {
  declare module.exports: $Exports<'csvtojson/browser/browser'>;
}
declare module 'csvtojson/coverage/block-navigation.js' {
  declare module.exports: $Exports<'csvtojson/coverage/block-navigation'>;
}
declare module 'csvtojson/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'csvtojson/coverage/lcov-report/block-navigation'>;
}
declare module 'csvtojson/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'csvtojson/coverage/lcov-report/prettify'>;
}
declare module 'csvtojson/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'csvtojson/coverage/lcov-report/sorter'>;
}
declare module 'csvtojson/coverage/prettify.js' {
  declare module.exports: $Exports<'csvtojson/coverage/prettify'>;
}
declare module 'csvtojson/coverage/sorter.js' {
  declare module.exports: $Exports<'csvtojson/coverage/sorter'>;
}
declare module 'csvtojson/index' {
  declare module.exports: $Exports<'csvtojson'>;
}
declare module 'csvtojson/index.js' {
  declare module.exports: $Exports<'csvtojson'>;
}
declare module 'csvtojson/v1/core/Converter.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/Converter'>;
}
declare module 'csvtojson/v1/core/CSVError.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/CSVError'>;
}
declare module 'csvtojson/v1/core/csvline.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/csvline'>;
}
declare module 'csvtojson/v1/core/dataToCSVLine.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/dataToCSVLine'>;
}
declare module 'csvtojson/v1/core/defaultParsers/index.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/defaultParsers/index'>;
}
declare module 'csvtojson/v1/core/defaultParsers/parser_array.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/defaultParsers/parser_array'>;
}
declare module 'csvtojson/v1/core/defaultParsers/parser_flat.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/defaultParsers/parser_flat'>;
}
declare module 'csvtojson/v1/core/defaultParsers/parser_json.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/defaultParsers/parser_json'>;
}
declare module 'csvtojson/v1/core/defaultParsers/parser_jsonarray.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/defaultParsers/parser_jsonarray'>;
}
declare module 'csvtojson/v1/core/defaultParsers/parser_omit.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/defaultParsers/parser_omit'>;
}
declare module 'csvtojson/v1/core/defParam.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/defParam'>;
}
declare module 'csvtojson/v1/core/fileline.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/fileline'>;
}
declare module 'csvtojson/v1/core/fileLineToCSVLine.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/fileLineToCSVLine'>;
}
declare module 'csvtojson/v1/core/filterRow.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/filterRow'>;
}
declare module 'csvtojson/v1/core/getDelimiter.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/getDelimiter'>;
}
declare module 'csvtojson/v1/core/getEol.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/getEol'>;
}
declare module 'csvtojson/v1/core/index.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/index'>;
}
declare module 'csvtojson/v1/core/linesToJson.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/linesToJson'>;
}
declare module 'csvtojson/v1/core/parser.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/parser'>;
}
declare module 'csvtojson/v1/core/parserMgr.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/parserMgr'>;
}
declare module 'csvtojson/v1/core/rowSplit.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/rowSplit'>;
}
declare module 'csvtojson/v1/core/worker.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/worker'>;
}
declare module 'csvtojson/v1/core/workerMgr.js' {
  declare module.exports: $Exports<'csvtojson/v1/core/workerMgr'>;
}
declare module 'csvtojson/v1/index.js' {
  declare module.exports: $Exports<'csvtojson/v1/index'>;
}
declare module 'csvtojson/v1/interfaces/cli/index.js' {
  declare module.exports: $Exports<'csvtojson/v1/interfaces/cli/index'>;
}
declare module 'csvtojson/v1/interfaces/cli/main.js' {
  declare module.exports: $Exports<'csvtojson/v1/interfaces/cli/main'>;
}
declare module 'csvtojson/v1/interfaces/index.js' {
  declare module.exports: $Exports<'csvtojson/v1/interfaces/index'>;
}
declare module 'csvtojson/v1/interfaces/web/index.js' {
  declare module.exports: $Exports<'csvtojson/v1/interfaces/web/index'>;
}
declare module 'csvtojson/v1/interfaces/web/webServer.js' {
  declare module.exports: $Exports<'csvtojson/v1/interfaces/web/webServer'>;
}
declare module 'csvtojson/v2/Converter.js' {
  declare module.exports: $Exports<'csvtojson/v2/Converter'>;
}
declare module 'csvtojson/v2/CSVError.js' {
  declare module.exports: $Exports<'csvtojson/v2/CSVError'>;
}
declare module 'csvtojson/v2/dataClean.js' {
  declare module.exports: $Exports<'csvtojson/v2/dataClean'>;
}
declare module 'csvtojson/v2/fileline.js' {
  declare module.exports: $Exports<'csvtojson/v2/fileline'>;
}
declare module 'csvtojson/v2/getEol.js' {
  declare module.exports: $Exports<'csvtojson/v2/getEol'>;
}
declare module 'csvtojson/v2/index.js' {
  declare module.exports: $Exports<'csvtojson/v2/index'>;
}
declare module 'csvtojson/v2/lineToJson.js' {
  declare module.exports: $Exports<'csvtojson/v2/lineToJson'>;
}
declare module 'csvtojson/v2/Parameters.js' {
  declare module.exports: $Exports<'csvtojson/v2/Parameters'>;
}
declare module 'csvtojson/v2/ParseRuntime.js' {
  declare module.exports: $Exports<'csvtojson/v2/ParseRuntime'>;
}
declare module 'csvtojson/v2/ProcessFork.js' {
  declare module.exports: $Exports<'csvtojson/v2/ProcessFork'>;
}
declare module 'csvtojson/v2/Processor.js' {
  declare module.exports: $Exports<'csvtojson/v2/Processor'>;
}
declare module 'csvtojson/v2/ProcessorLocal.js' {
  declare module.exports: $Exports<'csvtojson/v2/ProcessorLocal'>;
}
declare module 'csvtojson/v2/Result.js' {
  declare module.exports: $Exports<'csvtojson/v2/Result'>;
}
declare module 'csvtojson/v2/rowSplit.js' {
  declare module.exports: $Exports<'csvtojson/v2/rowSplit'>;
}
declare module 'csvtojson/v2/util.js' {
  declare module.exports: $Exports<'csvtojson/v2/util'>;
}
declare module 'csvtojson/v2/worker.js' {
  declare module.exports: $Exports<'csvtojson/v2/worker'>;
}
declare module 'csvtojson/webpack.config.js' {
  declare module.exports: $Exports<'csvtojson/webpack.config'>;
}
