// flow-typed signature: ca8427869cd4c8cb97c680ee03d74438
// flow-typed version: <<STUB>>/dom-to-image_v^2.6.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-to-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-to-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-to-image/bower_components/jquery/dist/jquery' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/dist/jquery.min' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax/jsonp' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax/load' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax/parseJSON' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax/parseXML' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax/script' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax/var/nonce' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax/var/rquery' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/ajax/xhr' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/attributes' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/attributes/attr' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/attributes/classes' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/attributes/prop' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/attributes/support' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/attributes/val' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/callbacks' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/core' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/core/access' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/core/init' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/core/parseHTML' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/core/ready' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/core/var/rsingleTag' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/addGetHookIf' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/curCSS' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/defaultDisplay' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/hiddenVisibleSelectors' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/support' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/swap' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/var/cssExpand' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/var/getStyles' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/var/isHidden' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/var/rmargin' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/css/var/rnumnonpx' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/data' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/data/accepts' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/data/Data' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/data/var/data_priv' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/data/var/data_user' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/deferred' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/deprecated' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/dimensions' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/effects' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/effects/animatedSelector' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/effects/Tween' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/event' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/event/ajax' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/event/alias' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/event/support' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/exports/amd' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/exports/global' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/intro' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/jquery' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/manipulation' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/manipulation/_evalUrl' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/manipulation/support' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/manipulation/var/rcheckableType' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/offset' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/outro' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/queue' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/queue/delay' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/selector-native' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/selector-sizzle' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/selector' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/serialize' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/sizzle/dist/sizzle' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/sizzle/dist/sizzle.min' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/traversing' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/traversing/findFilter' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/traversing/var/rneedsContext' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/arr' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/class2type' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/concat' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/hasOwn' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/indexOf' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/pnum' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/push' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/rnotwhite' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/slice' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/strundefined' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/support' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/var/toString' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/jquery/src/wrap' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/browser/canvas' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/imagediff' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/imagediff.min' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/js/imagediff' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/js/license' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/lib/jasmine/jasmine-html' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/lib/jasmine/jasmine' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/lib/jquery-1.6.4.min' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/js-imagediff/spec/ImageDiffSpec' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/ocrad-bower/ocrad' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/ocrad-bower/post' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/ocrad-bower/pre' {
  declare module.exports: any;
}

declare module 'dom-to-image/bower_components/ocrad-bower/worker' {
  declare module.exports: any;
}

declare module 'dom-to-image/dist/dom-to-image.min' {
  declare module.exports: any;
}

declare module 'dom-to-image/Gruntfile' {
  declare module.exports: any;
}

declare module 'dom-to-image/karma.conf' {
  declare module.exports: any;
}

declare module 'dom-to-image/spec/dom-to-image.spec' {
  declare module.exports: any;
}

declare module 'dom-to-image/src/dom-to-image' {
  declare module.exports: any;
}

declare module 'dom-to-image/test-lib/tesseract-1.0.10' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom-to-image/bower_components/jquery/dist/jquery.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/dist/jquery'>;
}
declare module 'dom-to-image/bower_components/jquery/dist/jquery.min.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/dist/jquery.min'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax/jsonp.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax/jsonp'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax/load.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax/load'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax/parseJSON.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax/parseJSON'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax/parseXML.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax/parseXML'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax/script.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax/script'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax/var/nonce.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax/var/nonce'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax/var/rquery.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax/var/rquery'>;
}
declare module 'dom-to-image/bower_components/jquery/src/ajax/xhr.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/ajax/xhr'>;
}
declare module 'dom-to-image/bower_components/jquery/src/attributes.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/attributes'>;
}
declare module 'dom-to-image/bower_components/jquery/src/attributes/attr.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/attributes/attr'>;
}
declare module 'dom-to-image/bower_components/jquery/src/attributes/classes.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/attributes/classes'>;
}
declare module 'dom-to-image/bower_components/jquery/src/attributes/prop.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/attributes/prop'>;
}
declare module 'dom-to-image/bower_components/jquery/src/attributes/support.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/attributes/support'>;
}
declare module 'dom-to-image/bower_components/jquery/src/attributes/val.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/attributes/val'>;
}
declare module 'dom-to-image/bower_components/jquery/src/callbacks.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/callbacks'>;
}
declare module 'dom-to-image/bower_components/jquery/src/core.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/core'>;
}
declare module 'dom-to-image/bower_components/jquery/src/core/access.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/core/access'>;
}
declare module 'dom-to-image/bower_components/jquery/src/core/init.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/core/init'>;
}
declare module 'dom-to-image/bower_components/jquery/src/core/parseHTML.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/core/parseHTML'>;
}
declare module 'dom-to-image/bower_components/jquery/src/core/ready.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/core/ready'>;
}
declare module 'dom-to-image/bower_components/jquery/src/core/var/rsingleTag.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/core/var/rsingleTag'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/addGetHookIf.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/addGetHookIf'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/curCSS.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/curCSS'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/defaultDisplay.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/defaultDisplay'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/hiddenVisibleSelectors.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/hiddenVisibleSelectors'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/support.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/support'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/swap.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/swap'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/var/cssExpand.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/var/cssExpand'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/var/getStyles.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/var/getStyles'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/var/isHidden.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/var/isHidden'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/var/rmargin.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/var/rmargin'>;
}
declare module 'dom-to-image/bower_components/jquery/src/css/var/rnumnonpx.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/css/var/rnumnonpx'>;
}
declare module 'dom-to-image/bower_components/jquery/src/data.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/data'>;
}
declare module 'dom-to-image/bower_components/jquery/src/data/accepts.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/data/accepts'>;
}
declare module 'dom-to-image/bower_components/jquery/src/data/Data.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/data/Data'>;
}
declare module 'dom-to-image/bower_components/jquery/src/data/var/data_priv.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/data/var/data_priv'>;
}
declare module 'dom-to-image/bower_components/jquery/src/data/var/data_user.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/data/var/data_user'>;
}
declare module 'dom-to-image/bower_components/jquery/src/deferred.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/deferred'>;
}
declare module 'dom-to-image/bower_components/jquery/src/deprecated.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/deprecated'>;
}
declare module 'dom-to-image/bower_components/jquery/src/dimensions.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/dimensions'>;
}
declare module 'dom-to-image/bower_components/jquery/src/effects.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/effects'>;
}
declare module 'dom-to-image/bower_components/jquery/src/effects/animatedSelector.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/effects/animatedSelector'>;
}
declare module 'dom-to-image/bower_components/jquery/src/effects/Tween.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/effects/Tween'>;
}
declare module 'dom-to-image/bower_components/jquery/src/event.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/event'>;
}
declare module 'dom-to-image/bower_components/jquery/src/event/ajax.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/event/ajax'>;
}
declare module 'dom-to-image/bower_components/jquery/src/event/alias.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/event/alias'>;
}
declare module 'dom-to-image/bower_components/jquery/src/event/support.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/event/support'>;
}
declare module 'dom-to-image/bower_components/jquery/src/exports/amd.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/exports/amd'>;
}
declare module 'dom-to-image/bower_components/jquery/src/exports/global.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/exports/global'>;
}
declare module 'dom-to-image/bower_components/jquery/src/intro.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/intro'>;
}
declare module 'dom-to-image/bower_components/jquery/src/jquery.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/jquery'>;
}
declare module 'dom-to-image/bower_components/jquery/src/manipulation.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/manipulation'>;
}
declare module 'dom-to-image/bower_components/jquery/src/manipulation/_evalUrl.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/manipulation/_evalUrl'>;
}
declare module 'dom-to-image/bower_components/jquery/src/manipulation/support.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/manipulation/support'>;
}
declare module 'dom-to-image/bower_components/jquery/src/manipulation/var/rcheckableType.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/manipulation/var/rcheckableType'>;
}
declare module 'dom-to-image/bower_components/jquery/src/offset.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/offset'>;
}
declare module 'dom-to-image/bower_components/jquery/src/outro.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/outro'>;
}
declare module 'dom-to-image/bower_components/jquery/src/queue.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/queue'>;
}
declare module 'dom-to-image/bower_components/jquery/src/queue/delay.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/queue/delay'>;
}
declare module 'dom-to-image/bower_components/jquery/src/selector-native.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/selector-native'>;
}
declare module 'dom-to-image/bower_components/jquery/src/selector-sizzle.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/selector-sizzle'>;
}
declare module 'dom-to-image/bower_components/jquery/src/selector.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/selector'>;
}
declare module 'dom-to-image/bower_components/jquery/src/serialize.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/serialize'>;
}
declare module 'dom-to-image/bower_components/jquery/src/sizzle/dist/sizzle.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/sizzle/dist/sizzle'>;
}
declare module 'dom-to-image/bower_components/jquery/src/sizzle/dist/sizzle.min.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/sizzle/dist/sizzle.min'>;
}
declare module 'dom-to-image/bower_components/jquery/src/traversing.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/traversing'>;
}
declare module 'dom-to-image/bower_components/jquery/src/traversing/findFilter.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/traversing/findFilter'>;
}
declare module 'dom-to-image/bower_components/jquery/src/traversing/var/rneedsContext.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/traversing/var/rneedsContext'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/arr.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/arr'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/class2type.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/class2type'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/concat.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/concat'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/hasOwn.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/hasOwn'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/indexOf.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/indexOf'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/pnum.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/pnum'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/push.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/push'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/rnotwhite.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/rnotwhite'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/slice.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/slice'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/strundefined.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/strundefined'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/support.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/support'>;
}
declare module 'dom-to-image/bower_components/jquery/src/var/toString.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/var/toString'>;
}
declare module 'dom-to-image/bower_components/jquery/src/wrap.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/jquery/src/wrap'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/browser/canvas.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/browser/canvas'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/imagediff.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/imagediff'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/imagediff.min.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/imagediff.min'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/js/imagediff.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/js/imagediff'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/js/license.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/js/license'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/lib/jasmine/jasmine-html.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/lib/jasmine/jasmine-html'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/lib/jasmine/jasmine.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/lib/jasmine/jasmine'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/lib/jquery-1.6.4.min.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/lib/jquery-1.6.4.min'>;
}
declare module 'dom-to-image/bower_components/js-imagediff/spec/ImageDiffSpec.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/js-imagediff/spec/ImageDiffSpec'>;
}
declare module 'dom-to-image/bower_components/ocrad-bower/ocrad.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/ocrad-bower/ocrad'>;
}
declare module 'dom-to-image/bower_components/ocrad-bower/post.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/ocrad-bower/post'>;
}
declare module 'dom-to-image/bower_components/ocrad-bower/pre.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/ocrad-bower/pre'>;
}
declare module 'dom-to-image/bower_components/ocrad-bower/worker.js' {
  declare module.exports: $Exports<'dom-to-image/bower_components/ocrad-bower/worker'>;
}
declare module 'dom-to-image/dist/dom-to-image.min.js' {
  declare module.exports: $Exports<'dom-to-image/dist/dom-to-image.min'>;
}
declare module 'dom-to-image/Gruntfile.js' {
  declare module.exports: $Exports<'dom-to-image/Gruntfile'>;
}
declare module 'dom-to-image/karma.conf.js' {
  declare module.exports: $Exports<'dom-to-image/karma.conf'>;
}
declare module 'dom-to-image/spec/dom-to-image.spec.js' {
  declare module.exports: $Exports<'dom-to-image/spec/dom-to-image.spec'>;
}
declare module 'dom-to-image/src/dom-to-image.js' {
  declare module.exports: $Exports<'dom-to-image/src/dom-to-image'>;
}
declare module 'dom-to-image/test-lib/tesseract-1.0.10.js' {
  declare module.exports: $Exports<'dom-to-image/test-lib/tesseract-1.0.10'>;
}
