// flow-typed signature: b7fc29c1d8e3c2ddd7223b5ee859aa8e
// flow-typed version: <<STUB>>/electron-store_v^1.3.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-store/index' {
  declare module.exports: $Exports<'electron-store'>;
}
declare module 'electron-store/index.js' {
  declare module.exports: $Exports<'electron-store'>;
}
