// flow-typed signature: a56f596803db558c08255640f2373e41
// flow-typed version: <<STUB>>/gifsicle_v^3.0.4/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gifsicle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gifsicle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gifsicle/cli' {
  declare module.exports: any;
}

declare module 'gifsicle/lib/index' {
  declare module.exports: any;
}

declare module 'gifsicle/lib/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gifsicle/cli.js' {
  declare module.exports: $Exports<'gifsicle/cli'>;
}
declare module 'gifsicle/index' {
  declare module.exports: $Exports<'gifsicle'>;
}
declare module 'gifsicle/index.js' {
  declare module.exports: $Exports<'gifsicle'>;
}
declare module 'gifsicle/lib/index.js' {
  declare module.exports: $Exports<'gifsicle/lib/index'>;
}
declare module 'gifsicle/lib/install.js' {
  declare module.exports: $Exports<'gifsicle/lib/install'>;
}
