// flow-typed signature: 86044aa5d18aa5e65df3c3f99baf9d0d
// flow-typed version: <<STUB>>/image-type_v^3.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'image-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'image-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'image-type/index' {
  declare module.exports: $Exports<'image-type'>;
}
declare module 'image-type/index.js' {
  declare module.exports: $Exports<'image-type'>;
}
