// flow-typed signature: 705c8ac7c9dd99b398a10dc91d976876
// flow-typed version: <<STUB>>/intro.js_v^2.9.3/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intro.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'intro.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intro.js/intro' {
  declare module.exports: any;
}

declare module 'intro.js/minified/intro.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intro.js/intro.js' {
  declare module.exports: $Exports<'intro.js/intro'>;
}
declare module 'intro.js/minified/intro.min.js' {
  declare module.exports: $Exports<'intro.js/minified/intro.min'>;
}
