// flow-typed signature: b673b3d84784f42ff4959e7efdc92402
// flow-typed version: <<STUB>>/leancloud-storage_v^3.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leancloud-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leancloud-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leancloud-storage/dist/av-live-query-min' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av-live-query-rn-min' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av-live-query-weapp-min' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av-live-query-weapp' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av-live-query' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av-min' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av-rn-min' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av-weapp-min' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av-weapp' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/av' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/acl' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/app-router' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/av' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/cache' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/captcha' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/cloudfunction' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/conversation' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/error' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/event' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/file' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/geopoint' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/index-live-query' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/index' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/init' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/insight' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/leaderboard' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/live-query' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/localstorage' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/object' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/op' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/polyfills/index-weapp' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/polyfills/index' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/promise' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/push' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/query' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/relation' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/request' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/role' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/search' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/status' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/ua/comments-browser' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/ua/comments' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/ua/index' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/uploader/cos' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/uploader/qiniu' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/uploader/s3' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/user' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/utils/index' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/utils/localstorage-browser' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/utils/localstorage-rn' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/utils/localstorage' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/utils/parse-base64-browser' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/utils/parse-base64' {
  declare module.exports: any;
}

declare module 'leancloud-storage/dist/node/version' {
  declare module.exports: any;
}

declare module 'leancloud-storage/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'leancloud-storage/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'leancloud-storage/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'leancloud-storage/live-query' {
  declare module.exports: any;
}

declare module 'leancloud-storage/webpack/browser' {
  declare module.exports: any;
}

declare module 'leancloud-storage/webpack/common' {
  declare module.exports: any;
}

declare module 'leancloud-storage/webpack/rn' {
  declare module.exports: any;
}

declare module 'leancloud-storage/webpack/weapp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leancloud-storage/dist/av-live-query-min.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-live-query-min'>;
}
declare module 'leancloud-storage/dist/av-live-query-rn-min.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-live-query-rn-min'>;
}
declare module 'leancloud-storage/dist/av-live-query-weapp-min.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-live-query-weapp-min'>;
}
declare module 'leancloud-storage/dist/av-live-query-weapp.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-live-query-weapp'>;
}
declare module 'leancloud-storage/dist/av-live-query.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-live-query'>;
}
declare module 'leancloud-storage/dist/av-min.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-min'>;
}
declare module 'leancloud-storage/dist/av-rn-min.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-rn-min'>;
}
declare module 'leancloud-storage/dist/av-weapp-min.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-weapp-min'>;
}
declare module 'leancloud-storage/dist/av-weapp.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av-weapp'>;
}
declare module 'leancloud-storage/dist/av.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/av'>;
}
declare module 'leancloud-storage/dist/node/acl.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/acl'>;
}
declare module 'leancloud-storage/dist/node/app-router.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/app-router'>;
}
declare module 'leancloud-storage/dist/node/av.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/av'>;
}
declare module 'leancloud-storage/dist/node/cache.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/cache'>;
}
declare module 'leancloud-storage/dist/node/captcha.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/captcha'>;
}
declare module 'leancloud-storage/dist/node/cloudfunction.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/cloudfunction'>;
}
declare module 'leancloud-storage/dist/node/conversation.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/conversation'>;
}
declare module 'leancloud-storage/dist/node/error.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/error'>;
}
declare module 'leancloud-storage/dist/node/event.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/event'>;
}
declare module 'leancloud-storage/dist/node/file.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/file'>;
}
declare module 'leancloud-storage/dist/node/geopoint.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/geopoint'>;
}
declare module 'leancloud-storage/dist/node/index-live-query.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/index-live-query'>;
}
declare module 'leancloud-storage/dist/node/index.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/index'>;
}
declare module 'leancloud-storage/dist/node/init.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/init'>;
}
declare module 'leancloud-storage/dist/node/insight.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/insight'>;
}
declare module 'leancloud-storage/dist/node/leaderboard.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/leaderboard'>;
}
declare module 'leancloud-storage/dist/node/live-query.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/live-query'>;
}
declare module 'leancloud-storage/dist/node/localstorage.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/localstorage'>;
}
declare module 'leancloud-storage/dist/node/object.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/object'>;
}
declare module 'leancloud-storage/dist/node/op.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/op'>;
}
declare module 'leancloud-storage/dist/node/polyfills/index-weapp.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/polyfills/index-weapp'>;
}
declare module 'leancloud-storage/dist/node/polyfills/index.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/polyfills/index'>;
}
declare module 'leancloud-storage/dist/node/promise.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/promise'>;
}
declare module 'leancloud-storage/dist/node/push.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/push'>;
}
declare module 'leancloud-storage/dist/node/query.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/query'>;
}
declare module 'leancloud-storage/dist/node/relation.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/relation'>;
}
declare module 'leancloud-storage/dist/node/request.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/request'>;
}
declare module 'leancloud-storage/dist/node/role.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/role'>;
}
declare module 'leancloud-storage/dist/node/search.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/search'>;
}
declare module 'leancloud-storage/dist/node/status.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/status'>;
}
declare module 'leancloud-storage/dist/node/ua/comments-browser.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/ua/comments-browser'>;
}
declare module 'leancloud-storage/dist/node/ua/comments.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/ua/comments'>;
}
declare module 'leancloud-storage/dist/node/ua/index.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/ua/index'>;
}
declare module 'leancloud-storage/dist/node/uploader/cos.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/uploader/cos'>;
}
declare module 'leancloud-storage/dist/node/uploader/qiniu.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/uploader/qiniu'>;
}
declare module 'leancloud-storage/dist/node/uploader/s3.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/uploader/s3'>;
}
declare module 'leancloud-storage/dist/node/user.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/user'>;
}
declare module 'leancloud-storage/dist/node/utils/index.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/utils/index'>;
}
declare module 'leancloud-storage/dist/node/utils/localstorage-browser.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/utils/localstorage-browser'>;
}
declare module 'leancloud-storage/dist/node/utils/localstorage-rn.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/utils/localstorage-rn'>;
}
declare module 'leancloud-storage/dist/node/utils/localstorage.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/utils/localstorage'>;
}
declare module 'leancloud-storage/dist/node/utils/parse-base64-browser.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/utils/parse-base64-browser'>;
}
declare module 'leancloud-storage/dist/node/utils/parse-base64.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/utils/parse-base64'>;
}
declare module 'leancloud-storage/dist/node/version.js' {
  declare module.exports: $Exports<'leancloud-storage/dist/node/version'>;
}
declare module 'leancloud-storage/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'leancloud-storage/docs/scripts/linenumber'>;
}
declare module 'leancloud-storage/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'leancloud-storage/docs/scripts/prettify/lang-css'>;
}
declare module 'leancloud-storage/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'leancloud-storage/docs/scripts/prettify/prettify'>;
}
declare module 'leancloud-storage/live-query.js' {
  declare module.exports: $Exports<'leancloud-storage/live-query'>;
}
declare module 'leancloud-storage/webpack/browser.js' {
  declare module.exports: $Exports<'leancloud-storage/webpack/browser'>;
}
declare module 'leancloud-storage/webpack/common.js' {
  declare module.exports: $Exports<'leancloud-storage/webpack/common'>;
}
declare module 'leancloud-storage/webpack/rn.js' {
  declare module.exports: $Exports<'leancloud-storage/webpack/rn'>;
}
declare module 'leancloud-storage/webpack/weapp.js' {
  declare module.exports: $Exports<'leancloud-storage/webpack/weapp'>;
}
