// flow-typed signature: 5f1232bb3a430435faae506a8cc7211f
// flow-typed version: <<STUB>>/msr_v^1.3.4/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'msr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'msr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'msr/AudioStreamRecorder/FlashAudioRecorder' {
  declare module.exports: any;
}

declare module 'msr/AudioStreamRecorder/lib/recorder' {
  declare module.exports: any;
}

declare module 'msr/AudioStreamRecorder/lib/recorder.js/recorder' {
  declare module.exports: any;
}

declare module 'msr/AudioStreamRecorder/lib/wavencoder/wavencoder' {
  declare module.exports: any;
}

declare module 'msr/AudioStreamRecorder/MediaRecorderWrapper' {
  declare module.exports: any;
}

declare module 'msr/AudioStreamRecorder/StereoAudioRecorder' {
  declare module.exports: any;
}

declare module 'msr/AudioStreamRecorder/StereoAudioRecorderHelper' {
  declare module.exports: any;
}

declare module 'msr/common/amd' {
  declare module.exports: any;
}

declare module 'msr/common/ConcatenateBlobs' {
  declare module.exports: any;
}

declare module 'msr/common/Cross-Browser-Declarations' {
  declare module.exports: any;
}

declare module 'msr/common/head' {
  declare module.exports: any;
}

declare module 'msr/common/MediaStreamRecorder' {
  declare module.exports: any;
}

declare module 'msr/common/MultiStreamRecorder' {
  declare module.exports: any;
}

declare module 'msr/common/ObjectStore' {
  declare module.exports: any;
}

declare module 'msr/common/OpentTokStreamRecorder' {
  declare module.exports: any;
}

declare module 'msr/FileSystem/FileReader' {
  declare module.exports: any;
}

declare module 'msr/FileSystem/FileWriter' {
  declare module.exports: any;
}

declare module 'msr/Gruntfile' {
  declare module.exports: any;
}

declare module 'msr/lib/AjaxRequest/AjaxRequest' {
  declare module.exports: any;
}

declare module 'msr/MediaStreamRecorder' {
  declare module.exports: any;
}

declare module 'msr/MediaStreamRecorder.min' {
  declare module.exports: any;
}

declare module 'msr/npm-test' {
  declare module.exports: any;
}

declare module 'msr/server' {
  declare module.exports: any;
}

declare module 'msr/VideoStreamRecorder/GifRecorder' {
  declare module.exports: any;
}

declare module 'msr/VideoStreamRecorder/lib/gif-encoder' {
  declare module.exports: any;
}

declare module 'msr/VideoStreamRecorder/lib/whammy' {
  declare module.exports: any;
}

declare module 'msr/VideoStreamRecorder/WhammyRecorder' {
  declare module.exports: any;
}

declare module 'msr/VideoStreamRecorder/WhammyRecorderHelper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'msr/AudioStreamRecorder/FlashAudioRecorder.js' {
  declare module.exports: $Exports<'msr/AudioStreamRecorder/FlashAudioRecorder'>;
}
declare module 'msr/AudioStreamRecorder/lib/recorder.js' {
  declare module.exports: $Exports<'msr/AudioStreamRecorder/lib/recorder'>;
}
declare module 'msr/AudioStreamRecorder/lib/recorder.js/recorder.js' {
  declare module.exports: $Exports<'msr/AudioStreamRecorder/lib/recorder.js/recorder'>;
}
declare module 'msr/AudioStreamRecorder/lib/wavencoder/wavencoder.js' {
  declare module.exports: $Exports<'msr/AudioStreamRecorder/lib/wavencoder/wavencoder'>;
}
declare module 'msr/AudioStreamRecorder/MediaRecorderWrapper.js' {
  declare module.exports: $Exports<'msr/AudioStreamRecorder/MediaRecorderWrapper'>;
}
declare module 'msr/AudioStreamRecorder/StereoAudioRecorder.js' {
  declare module.exports: $Exports<'msr/AudioStreamRecorder/StereoAudioRecorder'>;
}
declare module 'msr/AudioStreamRecorder/StereoAudioRecorderHelper.js' {
  declare module.exports: $Exports<'msr/AudioStreamRecorder/StereoAudioRecorderHelper'>;
}
declare module 'msr/common/amd.js' {
  declare module.exports: $Exports<'msr/common/amd'>;
}
declare module 'msr/common/ConcatenateBlobs.js' {
  declare module.exports: $Exports<'msr/common/ConcatenateBlobs'>;
}
declare module 'msr/common/Cross-Browser-Declarations.js' {
  declare module.exports: $Exports<'msr/common/Cross-Browser-Declarations'>;
}
declare module 'msr/common/head.js' {
  declare module.exports: $Exports<'msr/common/head'>;
}
declare module 'msr/common/MediaStreamRecorder.js' {
  declare module.exports: $Exports<'msr/common/MediaStreamRecorder'>;
}
declare module 'msr/common/MultiStreamRecorder.js' {
  declare module.exports: $Exports<'msr/common/MultiStreamRecorder'>;
}
declare module 'msr/common/ObjectStore.js' {
  declare module.exports: $Exports<'msr/common/ObjectStore'>;
}
declare module 'msr/common/OpentTokStreamRecorder.js' {
  declare module.exports: $Exports<'msr/common/OpentTokStreamRecorder'>;
}
declare module 'msr/FileSystem/FileReader.js' {
  declare module.exports: $Exports<'msr/FileSystem/FileReader'>;
}
declare module 'msr/FileSystem/FileWriter.js' {
  declare module.exports: $Exports<'msr/FileSystem/FileWriter'>;
}
declare module 'msr/Gruntfile.js' {
  declare module.exports: $Exports<'msr/Gruntfile'>;
}
declare module 'msr/lib/AjaxRequest/AjaxRequest.js' {
  declare module.exports: $Exports<'msr/lib/AjaxRequest/AjaxRequest'>;
}
declare module 'msr/MediaStreamRecorder.js' {
  declare module.exports: $Exports<'msr/MediaStreamRecorder'>;
}
declare module 'msr/MediaStreamRecorder.min.js' {
  declare module.exports: $Exports<'msr/MediaStreamRecorder.min'>;
}
declare module 'msr/npm-test.js' {
  declare module.exports: $Exports<'msr/npm-test'>;
}
declare module 'msr/server.js' {
  declare module.exports: $Exports<'msr/server'>;
}
declare module 'msr/VideoStreamRecorder/GifRecorder.js' {
  declare module.exports: $Exports<'msr/VideoStreamRecorder/GifRecorder'>;
}
declare module 'msr/VideoStreamRecorder/lib/gif-encoder.js' {
  declare module.exports: $Exports<'msr/VideoStreamRecorder/lib/gif-encoder'>;
}
declare module 'msr/VideoStreamRecorder/lib/whammy.js' {
  declare module.exports: $Exports<'msr/VideoStreamRecorder/lib/whammy'>;
}
declare module 'msr/VideoStreamRecorder/WhammyRecorder.js' {
  declare module.exports: $Exports<'msr/VideoStreamRecorder/WhammyRecorder'>;
}
declare module 'msr/VideoStreamRecorder/WhammyRecorderHelper.js' {
  declare module.exports: $Exports<'msr/VideoStreamRecorder/WhammyRecorderHelper'>;
}
