// flow-typed signature: f6702ed69bfbad2718e1d04af9fe83d4
// flow-typed version: <<STUB>>/muse-ui_v2.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'muse-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'muse-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'muse-ui/dist/muse-ui' {
  declare module.exports: any;
}

declare module 'muse-ui/src/appBar/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/autoComplete/filters' {
  declare module.exports: any;
}

declare module 'muse-ui/src/autoComplete/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/avatar/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/backTop/assist' {
  declare module.exports: any;
}

declare module 'muse-ui/src/backTop/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/badge/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/bottomNav/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/bottomSheet/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/breadCrumb/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/card/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/checkbox/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/chip/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/circularProgress/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/config' {
  declare module.exports: any;
}

declare module 'muse-ui/src/contentBlock/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/datePicker/dateUtils' {
  declare module.exports: any;
}

declare module 'muse-ui/src/datePicker/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/dialog/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/divider/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/drawer/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/dropDownMenu/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/flatButton/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/flexbox/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/floatButton/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/grid/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/gridList/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/icon/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/iconButton/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/iconMenu/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/infiniteScroll/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/abstractButton' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/clickoutside' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/focus' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/popup/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/popup/manager' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/popup/utils' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/resize' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/routerMixin' {
  declare module.exports: any;
}

declare module 'muse-ui/src/internal/scroll' {
  declare module.exports: any;
}

declare module 'muse-ui/src/linearProgress/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/list/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/menu/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/pagination/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/paper/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/picker/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/popover/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/popup/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/radio/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/raisedButton/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/refreshControl/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/selectField/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/slider/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/snackbar/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/stepper/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/subHeader/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/switch/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/table/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/tabs/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/textField/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/timeLine/assist' {
  declare module.exports: any;
}

declare module 'muse-ui/src/timeLine/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/timePicker/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/timePicker/timeUtils' {
  declare module.exports: any;
}

declare module 'muse-ui/src/toast/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/tooltip/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/utils/classList' {
  declare module.exports: any;
}

declare module 'muse-ui/src/utils/colors' {
  declare module.exports: any;
}

declare module 'muse-ui/src/utils/domUtil' {
  declare module.exports: any;
}

declare module 'muse-ui/src/utils/drag' {
  declare module.exports: any;
}

declare module 'muse-ui/src/utils/index' {
  declare module.exports: any;
}

declare module 'muse-ui/src/utils/translate' {
  declare module.exports: any;
}

declare module 'muse-ui/test/unit/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'muse-ui/test/unit/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'muse-ui/test/unit/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify' {
  declare module.exports: any;
}

declare module 'muse-ui/test/unit/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter' {
  declare module.exports: any;
}

declare module 'muse-ui/test/unit/index' {
  declare module.exports: any;
}

declare module 'muse-ui/test/unit/karma.conf' {
  declare module.exports: any;
}

declare module 'muse-ui/test/unit/specs/appBar.spec' {
  declare module.exports: any;
}

declare module 'muse-ui/test/unit/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'muse-ui/dist/muse-ui.js' {
  declare module.exports: $Exports<'muse-ui/dist/muse-ui'>;
}
declare module 'muse-ui/src/appBar/index.js' {
  declare module.exports: $Exports<'muse-ui/src/appBar/index'>;
}
declare module 'muse-ui/src/autoComplete/filters.js' {
  declare module.exports: $Exports<'muse-ui/src/autoComplete/filters'>;
}
declare module 'muse-ui/src/autoComplete/index.js' {
  declare module.exports: $Exports<'muse-ui/src/autoComplete/index'>;
}
declare module 'muse-ui/src/avatar/index.js' {
  declare module.exports: $Exports<'muse-ui/src/avatar/index'>;
}
declare module 'muse-ui/src/backTop/assist.js' {
  declare module.exports: $Exports<'muse-ui/src/backTop/assist'>;
}
declare module 'muse-ui/src/backTop/index.js' {
  declare module.exports: $Exports<'muse-ui/src/backTop/index'>;
}
declare module 'muse-ui/src/badge/index.js' {
  declare module.exports: $Exports<'muse-ui/src/badge/index'>;
}
declare module 'muse-ui/src/bottomNav/index.js' {
  declare module.exports: $Exports<'muse-ui/src/bottomNav/index'>;
}
declare module 'muse-ui/src/bottomSheet/index.js' {
  declare module.exports: $Exports<'muse-ui/src/bottomSheet/index'>;
}
declare module 'muse-ui/src/breadCrumb/index.js' {
  declare module.exports: $Exports<'muse-ui/src/breadCrumb/index'>;
}
declare module 'muse-ui/src/card/index.js' {
  declare module.exports: $Exports<'muse-ui/src/card/index'>;
}
declare module 'muse-ui/src/checkbox/index.js' {
  declare module.exports: $Exports<'muse-ui/src/checkbox/index'>;
}
declare module 'muse-ui/src/chip/index.js' {
  declare module.exports: $Exports<'muse-ui/src/chip/index'>;
}
declare module 'muse-ui/src/circularProgress/index.js' {
  declare module.exports: $Exports<'muse-ui/src/circularProgress/index'>;
}
declare module 'muse-ui/src/config.js' {
  declare module.exports: $Exports<'muse-ui/src/config'>;
}
declare module 'muse-ui/src/contentBlock/index.js' {
  declare module.exports: $Exports<'muse-ui/src/contentBlock/index'>;
}
declare module 'muse-ui/src/datePicker/dateUtils.js' {
  declare module.exports: $Exports<'muse-ui/src/datePicker/dateUtils'>;
}
declare module 'muse-ui/src/datePicker/index.js' {
  declare module.exports: $Exports<'muse-ui/src/datePicker/index'>;
}
declare module 'muse-ui/src/dialog/index.js' {
  declare module.exports: $Exports<'muse-ui/src/dialog/index'>;
}
declare module 'muse-ui/src/divider/index.js' {
  declare module.exports: $Exports<'muse-ui/src/divider/index'>;
}
declare module 'muse-ui/src/drawer/index.js' {
  declare module.exports: $Exports<'muse-ui/src/drawer/index'>;
}
declare module 'muse-ui/src/dropDownMenu/index.js' {
  declare module.exports: $Exports<'muse-ui/src/dropDownMenu/index'>;
}
declare module 'muse-ui/src/flatButton/index.js' {
  declare module.exports: $Exports<'muse-ui/src/flatButton/index'>;
}
declare module 'muse-ui/src/flexbox/index.js' {
  declare module.exports: $Exports<'muse-ui/src/flexbox/index'>;
}
declare module 'muse-ui/src/floatButton/index.js' {
  declare module.exports: $Exports<'muse-ui/src/floatButton/index'>;
}
declare module 'muse-ui/src/grid/index.js' {
  declare module.exports: $Exports<'muse-ui/src/grid/index'>;
}
declare module 'muse-ui/src/gridList/index.js' {
  declare module.exports: $Exports<'muse-ui/src/gridList/index'>;
}
declare module 'muse-ui/src/icon/index.js' {
  declare module.exports: $Exports<'muse-ui/src/icon/index'>;
}
declare module 'muse-ui/src/iconButton/index.js' {
  declare module.exports: $Exports<'muse-ui/src/iconButton/index'>;
}
declare module 'muse-ui/src/iconMenu/index.js' {
  declare module.exports: $Exports<'muse-ui/src/iconMenu/index'>;
}
declare module 'muse-ui/src/index.js' {
  declare module.exports: $Exports<'muse-ui/src/index'>;
}
declare module 'muse-ui/src/infiniteScroll/index.js' {
  declare module.exports: $Exports<'muse-ui/src/infiniteScroll/index'>;
}
declare module 'muse-ui/src/internal/abstractButton.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/abstractButton'>;
}
declare module 'muse-ui/src/internal/clickoutside.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/clickoutside'>;
}
declare module 'muse-ui/src/internal/focus.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/focus'>;
}
declare module 'muse-ui/src/internal/popup/index.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/popup/index'>;
}
declare module 'muse-ui/src/internal/popup/manager.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/popup/manager'>;
}
declare module 'muse-ui/src/internal/popup/utils.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/popup/utils'>;
}
declare module 'muse-ui/src/internal/resize.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/resize'>;
}
declare module 'muse-ui/src/internal/routerMixin.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/routerMixin'>;
}
declare module 'muse-ui/src/internal/scroll.js' {
  declare module.exports: $Exports<'muse-ui/src/internal/scroll'>;
}
declare module 'muse-ui/src/linearProgress/index.js' {
  declare module.exports: $Exports<'muse-ui/src/linearProgress/index'>;
}
declare module 'muse-ui/src/list/index.js' {
  declare module.exports: $Exports<'muse-ui/src/list/index'>;
}
declare module 'muse-ui/src/menu/index.js' {
  declare module.exports: $Exports<'muse-ui/src/menu/index'>;
}
declare module 'muse-ui/src/pagination/index.js' {
  declare module.exports: $Exports<'muse-ui/src/pagination/index'>;
}
declare module 'muse-ui/src/paper/index.js' {
  declare module.exports: $Exports<'muse-ui/src/paper/index'>;
}
declare module 'muse-ui/src/picker/index.js' {
  declare module.exports: $Exports<'muse-ui/src/picker/index'>;
}
declare module 'muse-ui/src/popover/index.js' {
  declare module.exports: $Exports<'muse-ui/src/popover/index'>;
}
declare module 'muse-ui/src/popup/index.js' {
  declare module.exports: $Exports<'muse-ui/src/popup/index'>;
}
declare module 'muse-ui/src/radio/index.js' {
  declare module.exports: $Exports<'muse-ui/src/radio/index'>;
}
declare module 'muse-ui/src/raisedButton/index.js' {
  declare module.exports: $Exports<'muse-ui/src/raisedButton/index'>;
}
declare module 'muse-ui/src/refreshControl/index.js' {
  declare module.exports: $Exports<'muse-ui/src/refreshControl/index'>;
}
declare module 'muse-ui/src/selectField/index.js' {
  declare module.exports: $Exports<'muse-ui/src/selectField/index'>;
}
declare module 'muse-ui/src/slider/index.js' {
  declare module.exports: $Exports<'muse-ui/src/slider/index'>;
}
declare module 'muse-ui/src/snackbar/index.js' {
  declare module.exports: $Exports<'muse-ui/src/snackbar/index'>;
}
declare module 'muse-ui/src/stepper/index.js' {
  declare module.exports: $Exports<'muse-ui/src/stepper/index'>;
}
declare module 'muse-ui/src/subHeader/index.js' {
  declare module.exports: $Exports<'muse-ui/src/subHeader/index'>;
}
declare module 'muse-ui/src/switch/index.js' {
  declare module.exports: $Exports<'muse-ui/src/switch/index'>;
}
declare module 'muse-ui/src/table/index.js' {
  declare module.exports: $Exports<'muse-ui/src/table/index'>;
}
declare module 'muse-ui/src/tabs/index.js' {
  declare module.exports: $Exports<'muse-ui/src/tabs/index'>;
}
declare module 'muse-ui/src/textField/index.js' {
  declare module.exports: $Exports<'muse-ui/src/textField/index'>;
}
declare module 'muse-ui/src/timeLine/assist.js' {
  declare module.exports: $Exports<'muse-ui/src/timeLine/assist'>;
}
declare module 'muse-ui/src/timeLine/index.js' {
  declare module.exports: $Exports<'muse-ui/src/timeLine/index'>;
}
declare module 'muse-ui/src/timePicker/index.js' {
  declare module.exports: $Exports<'muse-ui/src/timePicker/index'>;
}
declare module 'muse-ui/src/timePicker/timeUtils.js' {
  declare module.exports: $Exports<'muse-ui/src/timePicker/timeUtils'>;
}
declare module 'muse-ui/src/toast/index.js' {
  declare module.exports: $Exports<'muse-ui/src/toast/index'>;
}
declare module 'muse-ui/src/tooltip/index.js' {
  declare module.exports: $Exports<'muse-ui/src/tooltip/index'>;
}
declare module 'muse-ui/src/utils/classList.js' {
  declare module.exports: $Exports<'muse-ui/src/utils/classList'>;
}
declare module 'muse-ui/src/utils/colors.js' {
  declare module.exports: $Exports<'muse-ui/src/utils/colors'>;
}
declare module 'muse-ui/src/utils/domUtil.js' {
  declare module.exports: $Exports<'muse-ui/src/utils/domUtil'>;
}
declare module 'muse-ui/src/utils/drag.js' {
  declare module.exports: $Exports<'muse-ui/src/utils/drag'>;
}
declare module 'muse-ui/src/utils/index.js' {
  declare module.exports: $Exports<'muse-ui/src/utils/index'>;
}
declare module 'muse-ui/src/utils/translate.js' {
  declare module.exports: $Exports<'muse-ui/src/utils/translate'>;
}
declare module 'muse-ui/test/unit/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'muse-ui/test/unit/coverage/lcov-report/prettify'>;
}
declare module 'muse-ui/test/unit/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'muse-ui/test/unit/coverage/lcov-report/sorter'>;
}
declare module 'muse-ui/test/unit/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify.js' {
  declare module.exports: $Exports<'muse-ui/test/unit/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify'>;
}
declare module 'muse-ui/test/unit/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter.js' {
  declare module.exports: $Exports<'muse-ui/test/unit/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter'>;
}
declare module 'muse-ui/test/unit/index.js' {
  declare module.exports: $Exports<'muse-ui/test/unit/index'>;
}
declare module 'muse-ui/test/unit/karma.conf.js' {
  declare module.exports: $Exports<'muse-ui/test/unit/karma.conf'>;
}
declare module 'muse-ui/test/unit/specs/appBar.spec.js' {
  declare module.exports: $Exports<'muse-ui/test/unit/specs/appBar.spec'>;
}
declare module 'muse-ui/test/unit/util.js' {
  declare module.exports: $Exports<'muse-ui/test/unit/util'>;
}
