// flow-typed signature: e42450c521bbf9ee333d2b7bd308c84d
// flow-typed version: <<STUB>>/node-unzip-2_v^0.2.7/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-unzip-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-unzip-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-unzip-2/lib/entry' {
  declare module.exports: any;
}

declare module 'node-unzip-2/lib/extract' {
  declare module.exports: any;
}

declare module 'node-unzip-2/lib/parse' {
  declare module.exports: any;
}

declare module 'node-unzip-2/test/compressed' {
  declare module.exports: any;
}

declare module 'node-unzip-2/test/fileSizeUnknownFlag' {
  declare module.exports: any;
}

declare module 'node-unzip-2/test/pipeSingleEntry' {
  declare module.exports: any;
}

declare module 'node-unzip-2/test/uncompressed' {
  declare module.exports: any;
}

declare module 'node-unzip-2/unzip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-unzip-2/lib/entry.js' {
  declare module.exports: $Exports<'node-unzip-2/lib/entry'>;
}
declare module 'node-unzip-2/lib/extract.js' {
  declare module.exports: $Exports<'node-unzip-2/lib/extract'>;
}
declare module 'node-unzip-2/lib/parse.js' {
  declare module.exports: $Exports<'node-unzip-2/lib/parse'>;
}
declare module 'node-unzip-2/test/compressed.js' {
  declare module.exports: $Exports<'node-unzip-2/test/compressed'>;
}
declare module 'node-unzip-2/test/fileSizeUnknownFlag.js' {
  declare module.exports: $Exports<'node-unzip-2/test/fileSizeUnknownFlag'>;
}
declare module 'node-unzip-2/test/pipeSingleEntry.js' {
  declare module.exports: $Exports<'node-unzip-2/test/pipeSingleEntry'>;
}
declare module 'node-unzip-2/test/uncompressed.js' {
  declare module.exports: $Exports<'node-unzip-2/test/uncompressed'>;
}
declare module 'node-unzip-2/unzip.js' {
  declare module.exports: $Exports<'node-unzip-2/unzip'>;
}
