// flow-typed signature: a3fa85ab10b229eac8f622c44ede453c
// flow-typed version: <<STUB>>/node-machine-id_v^1.1.10/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-machine-id'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-machine-id' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-machine-id/dist/index' {
  declare module.exports: any;
}

declare module 'node-machine-id/tests/index' {
  declare module.exports: any;
}

declare module 'node-machine-id/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-machine-id/dist/index.js' {
  declare module.exports: $Exports<'node-machine-id/dist/index'>;
}
declare module 'node-machine-id/index' {
  declare module.exports: $Exports<'node-machine-id'>;
}
declare module 'node-machine-id/index.js' {
  declare module.exports: $Exports<'node-machine-id'>;
}
declare module 'node-machine-id/tests/index.js' {
  declare module.exports: $Exports<'node-machine-id/tests/index'>;
}
declare module 'node-machine-id/webpack.config.babel.js' {
  declare module.exports: $Exports<'node-machine-id/webpack.config.babel'>;
}
