// flow-typed signature: db752863b2dee32a0433d8072f8e1ac4
// flow-typed version: <<STUB>>/particles.js_v^2.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'particles.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'particles.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'particles.js/demo/js/app' {
  declare module.exports: any;
}

declare module 'particles.js/demo/js/lib/stats' {
  declare module.exports: any;
}

declare module 'particles.js/particles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'particles.js/demo/js/app.js' {
  declare module.exports: $Exports<'particles.js/demo/js/app'>;
}
declare module 'particles.js/demo/js/lib/stats.js' {
  declare module.exports: $Exports<'particles.js/demo/js/lib/stats'>;
}
declare module 'particles.js/particles.js' {
  declare module.exports: $Exports<'particles.js/particles'>;
}
