// flow-typed signature: ee68d512825b2848677a32d27e66448c
// flow-typed version: <<STUB>>/sql.js_v^0.5.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sql.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sql.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sql.js/js/api' {
  declare module.exports: any;
}

declare module 'sql.js/js/shell-post' {
  declare module.exports: any;
}

declare module 'sql.js/js/shell-pre' {
  declare module.exports: any;
}

declare module 'sql.js/js/sql-debug' {
  declare module.exports: any;
}

declare module 'sql.js/js/sql-memory-growth' {
  declare module.exports: any;
}

declare module 'sql.js/js/sql-optimized' {
  declare module.exports: any;
}

declare module 'sql.js/js/sql' {
  declare module.exports: any;
}

declare module 'sql.js/js/worker' {
  declare module.exports: any;
}

declare module 'sql.js/js/worker.sql' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sql.js/js/api.js' {
  declare module.exports: $Exports<'sql.js/js/api'>;
}
declare module 'sql.js/js/shell-post.js' {
  declare module.exports: $Exports<'sql.js/js/shell-post'>;
}
declare module 'sql.js/js/shell-pre.js' {
  declare module.exports: $Exports<'sql.js/js/shell-pre'>;
}
declare module 'sql.js/js/sql-debug.js' {
  declare module.exports: $Exports<'sql.js/js/sql-debug'>;
}
declare module 'sql.js/js/sql-memory-growth.js' {
  declare module.exports: $Exports<'sql.js/js/sql-memory-growth'>;
}
declare module 'sql.js/js/sql-optimized.js' {
  declare module.exports: $Exports<'sql.js/js/sql-optimized'>;
}
declare module 'sql.js/js/sql.js' {
  declare module.exports: $Exports<'sql.js/js/sql'>;
}
declare module 'sql.js/js/worker.js' {
  declare module.exports: $Exports<'sql.js/js/worker'>;
}
declare module 'sql.js/js/worker.sql.js' {
  declare module.exports: $Exports<'sql.js/js/worker.sql'>;
}
