// flow-typed signature: 1bf0872bf6c4506aaa4afdef78e69f8b
// flow-typed version: <<STUB>>/vue-aplayer_v^1.5.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-aplayer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-aplayer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-aplayer/dist/vue-aplayer.min' {
  declare module.exports: any;
}

declare module 'vue-aplayer/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-aplayer/dist/vue-aplayer.min.js' {
  declare module.exports: $Exports<'vue-aplayer/dist/vue-aplayer.min'>;
}
declare module 'vue-aplayer/src/utils.js' {
  declare module.exports: $Exports<'vue-aplayer/src/utils'>;
}
