// flow-typed signature: 5548ac5b3593d0ffb71d590bfc14aba7
// flow-typed version: <<STUB>>/vue-electron_v^1.0.6/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vue-electron/index' {
  declare module.exports: $Exports<'vue-electron'>;
}
declare module 'vue-electron/index.js' {
  declare module.exports: $Exports<'vue-electron'>;
}
