// flow-typed signature: 3bff4661ae8823e72a4f34c9c7a8fa9d
// flow-typed version: <<STUB>>/vue-lever_v^0.1.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-lever'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-lever' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-lever/dist/lever' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-lever/dist/lever.js' {
  declare module.exports: $Exports<'vue-lever/dist/lever'>;
}
