// flow-typed signature: a4f524d398b0af555f0e2e5077aef3fe
// flow-typed version: <<STUB>>/vue-events_v^3.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-events/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-events/dist/index.js' {
  declare module.exports: $Exports<'vue-events/dist/index'>;
}
