// flow-typed signature: 414e9a1658730c374bed520d0910f6be
// flow-typed version: <<STUB>>/vuedraggable_v^2.16.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuedraggable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuedraggable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuedraggable/dist/vuedraggable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuedraggable/dist/vuedraggable.js' {
  declare module.exports: $Exports<'vuedraggable/dist/vuedraggable'>;
}
