// flow-typed signature: 8d38d02a6bed1904937a35f38b2bb9c6
// flow-typed version: <<STUB>>/zip-folder_v^1.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zip-folder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zip-folder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zip-folder/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zip-folder/index' {
  declare module.exports: $Exports<'zip-folder'>;
}
declare module 'zip-folder/index.js' {
  declare module.exports: $Exports<'zip-folder'>;
}
declare module 'zip-folder/tests.js' {
  declare module.exports: $Exports<'zip-folder/tests'>;
}
