on: push

name: test

jobs:
  test:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 3

      # Use this GitHub Action
      - name: Check package version
        id: latest
        uses: blacktop/get-latest-version-action@v1

      - name: Install Package dependencies
        run: echo '${{ toJson(steps.latest.outputs) }}'
